/**
 * GeoJSON `country_name` values eligible for the globe country filter.
 * Keep in sync with oceanops-simple-map/src/countryFilters.ts (ALL_COUNTRIES).
 */
export const FILTERABLE_GEO_COUNTRIES = [
  'ARGENTINA',
  'AUSTRALIA',
  'BAHAMAS',
  'BANGLADESH',
  'BELGIUM',
  'BERMUDA',
  'BRAZIL',
  'BULGARIA',
  'CANADA',
  'CHILE',
  'CHINA',
  'COLOMBIA',
  'COOK ISLANDS',
  'CROATIA',
  'CUBA',
  'DENMARK',
  'EUROPE',
  'FAROE IS.',
  'FIJI',
  'FINLAND',
  'FRANCE',
  'GERMANY',
  'GREECE',
  'GUINEA-BISSAU',
  'ICELAND',
  'INDIA',
  'INDONESIA',
  'IRELAND',
  'ISRAEL',
  'ITALY',
  'JAPAN',
  'JORDAN',
  'KIRIBATI',
  'MALTA',
  'MARSHALL IS.',
  'MAURITIUS',
  'MEXICO',
  'MICRONESIA',
  'NAURU',
  'NETHERLANDS',
  'NEW ZEALAND',
  'NORWAY',
  'PANAMA',
  'PERU',
  'PHILIPPINES',
  'PNG',
  'POLAND',
  'PORTUGAL',
  'PUERTO RICO',
  'RUSSIA',
  'SINGAPORE',
  'SLOVENIA',
  'SOUTH AFRICA',
  'SOUTH KOREA',
  'SPAIN',
  'SWEDEN',
  'TANZANIA',
  'THAILAND',
  'TONGA',
  'TUVALU',
  'UAE',
  'UK',
  'UKRAINE',
  'URUGUAY',
  'USA',
  'VANUATU',
  'VIET NAM',
  'WALLIS/FUTUNA',
]
