-- Pending OceanSITES rewrite
-- @where (pending)
-- t.network LIKE '%OceanSITES%'
-- AND t.country IS NOT NULL
-- AND TRIM(t.country) <> ''
-- AND t.country_iso_code2 IS NOT NULL
-- AND TRIM(t.country_iso_code2) <> ''
-- AND PARTNER_COUNTRY_ISO_EXPR(country_iso_code2) IS NOT NULL
-- @geojson (pending — latest deployment per WMO)
-- WITH ranked AS (
--   SELECT
--     ptf.id AS ptf_id,
--     ptf.ref,
--     ptf_deployment.depl_date,
--     ptf_deployment.lat,
--     ptf_deployment.lon,
--     wmo.wmo,
--     t.ptf_model,
--     t.country,
--     t.country_iso_code2,
--     ROW_NUMBER() OVER (
--       PARTITION BY wmo.wmo
--       ORDER BY ptf_deployment.depl_date DESC
--     ) AS rn
--   FROM oceanops.ptf
--   JOIN oceanops.ptf_deployment
--     ON ptf.ptf_depl_id = ptf_deployment.id
--   LEFT JOIN oceanops.wmo
--     ON wmo.ptf_id = ptf.id
--   JOIN oceanops.v_ptf_loc_n t
--     ON t.ptf_id = ptf.id
--   WHERE {{WHERE}}
-- )
-- SELECT jsonb_build_object(
--   'type', 'FeatureCollection',
--   'features', COALESCE(jsonb_agg(
--     jsonb_build_object(
--       'type', 'Feature',
--       'geometry', ST_AsGeoJSON(t.shape)::jsonb,
--       'properties', jsonb_build_object(
--         'category', 'oceansites',
--         'ptf_id', t.ptf_id,
--         'ptf_ref', t.ptf_ref,
--         'ptf_model', t.ptf_model,
--         'wmo', t.wmo,
--         'depl_date', to_char(t.depl_date, 'YYYY-MM-DD'),
--         'country_name', t.country,
--         'country_iso_reporting', PARTNER_COUNTRY_ISO_EXPR,
--         'country_ship', rv.ship_country,
--         'country_sensor_provider', sp.sensor_provider
--       )
--     )
--   ), '[]'::jsonb)
-- )
-- FROM (
--   SELECT
--     r.*,
--     ST_SetSRID(ST_MakePoint(r.lon, r.lat), 4326) AS shape
--   FROM ranked r
--   WHERE r.wmo IS NULL OR r.rn = 1
-- ) AS t
-- LEFT JOIN (
--   SELECT DISTINCT ON (ptf_id) ptf_id, ship_country
--   FROM oceanops.v_ptf_depl_rv
--   ORDER BY ptf_id, deployment_date DESC NULLS LAST
-- ) rv ON t.ptf_id = rv.ptf_id
-- LEFT JOIN (
--   SELECT DISTINCT ON (ptf_id) ptf_id, sensor_country
--   FROM oceanops.v_sensor_provider
--   ORDER BY ptf_id, sensor_model
-- ) sp ON t.ptf_id = sp.ptf_id;
-- @partner (pending)
-- WITH ranked AS ( ... same as geojson ranked CTE ... )
-- SELECT PARTNER_COUNTRY_ISO_EXPR AS country_iso_code2, COUNT(*)::int
-- FROM ( SELECT r.country, r.country_iso_code2 FROM ranked r WHERE r.wmo IS NULL OR r.rn = 1 ) AS t
-- GROUP BY 1
-- HAVING PARTNER_COUNTRY_ISO_EXPR IS NOT NULL
-- ORDER BY 1;